[project]
name = "manim-testing"
version = "0.0.0"
description = "Project for messing around and testing things in Manim"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "manim>=0.19.0",
]
